version: '3'
services:
  mysql:
    image: "mariadb:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - "./mariadb:/docker-entrypoint-initdb.d/"
    expose:
      - "3306"
    #ports:
      #- "3305:3306"
  web:
    build: .
    depends_on:
      - mysql
    links:
      - mysql
    ports:
     - "7001:7001"
    command: sh -c './wait-for-it.sh -t 0 mysql:3306 -- npm start'
