version: '3'
services:
  mysql:
    image: "mariadb:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - "./mariadb:/docker-entrypoint-initdb.d/"
    #ports:
      #- "3305:3306"
  web:
    build: .
    depends_on:
      - mysql
    links:
      - mysql
    ports:
     - "7001:7001"